---
- name: desktop-gnome - install gnome desktop
  apt:
    name: vanilla-gnome-desktop

- name: desktop-gnome - stop gdm
  systemd:
    name: gdm
    state: stopped

- name: desktop-gnome - disable gdm
  systemd:
    name: gdm
    enabled: false
  changed_when: false                  # workaround
