---
- name: check if we're running supported os
  assert:
    fail_msg: "{{ role_name }} only supports Ubuntu 20.04, 21.04, 21.10 and Fedora 34!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} \
                  version {{ ansible_distribution_version }}"
    quiet: not ansible_check_mode
    that: ( ansible_distribution|lower == "ubuntu" and
            ansible_distribution_version in ["20.04", "21.04", "21.10"] ) or
          ( ansible_distribution|lower == "fedora" and
            ansible_distribution_version in ["34"] )

# desktop for os

- name: include desktop family
  include: "{{ ansible_os_family | lower }}.yml"

# xrdp sound

- name: install xrdp sound
  include: sound.yml
  when:
    - xrdp_server_sound_enable
    - ansible_os_family | lower == "debian"

# xrdp config

- name: update xrdp config
  include: xrdp-config.yml

# dconf

- name: copy out dconf defaults
  copy:
    src: dconf/
    dest: /etc/dconf/
    mode: 0644
    directory_mode: 0755
    force: true
  register: dconf_config

- name: regenerate dconf when it has changed
  command: dconf update
  when: dconf_config is changed

# polkit

- name: copy out policy changes
  copy:
    src: polkit-1/
    dest: /etc/polkit-1/
    mode: 0644
    directory_mode: 0755
    force: true

# Xwrapper.config

- name: allow x11 login, only needed for fedora
  ini_file:
    path: /etc/X11/Xwrapper.config
    section: null
    option: allowed_users
    value: console
    mode: 0644

# suspend

- name: disable suspend
  systemd:
    name: '{{ item }}'
    masked: true
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
  register: disable_sleep

- name: restart logind
  systemd:
    name: systemd-logind
    state: restarted
  when: disable_sleep is changed
