---
- name: check if we're running supported os
  assert:
    fail_msg: "{{ role_name }} only supports ubuntu versions 20.04!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} \
                  version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      - ansible_distribution|lower == "ubuntu"
      - ansible_distribution_version|int in [20]

- name: turn on unattended upgrades, since we turn off user notifications
  apt:
    name:
      - gnome-backgrounds
      - unattended-upgrades
    cache_valid_time: 3600
    update_cache: true

- name: install xrdp from apt
  include: xrdp-apt.yml

- name: install xrdp sound
  include: sound.yml
  when: xrdp_server_sound_enable

- name: update xrdp config
  include: xrdp-config.yml

- name: install desktop environment
  include: 'desktop_{{ xrdp_server_desktop_environment }}.yml'

- name: copy out dconf defaults
  copy:
    src: dconf/
    dest: /etc/dconf/
    mode: 0644
    directory_mode: 0755
    force: true
  register: dconf_config

- name: regenerate dconf when it has changed
  command: dconf update
  when: dconf_config is changed

- name: copy out policy changes
  copy:
    src: polkit-1/
    dest: /etc/polkit-1/
    mode: 0644
    directory_mode: 0755
    force: true

- name: disable suspend
  systemd:
    name: '{{ item }}'
    masked: true
  loop:
    - sleep
    - suspend
    - hibernate
    - hybrid-sleep
  register: disable_sleep

- name: restart logind
  systemd:
    name: systemd-logind
    state: restarted
  when: disable_sleep is changed
