---
- name: xrdp-config - add norwegian language support
  copy:
    src: xrdp/km-00000414.ini
    dest: /etc/xrdp/km-00000414.ini
    mode: 0644
  register: keyboard_file

## xrdp_keyboard.ini

- name: xrdp-config - add norwegian to xrdp_keyboard.ini
  ini_file:
    path: /etc/xrdp/xrdp_keyboard.ini
    section: '{{ item.s }}'
    option: '{{ item.o }}'
    value: '{{ item.v }}'
    no_extra_spaces: true
    mode: 0644
  register: keyboard_config
  loop:
    - s: 'default_rdp_layouts'
      o: 'rdp_layout_no'
      v: '0x00000414'
    - s: 'default_layouts_map'
      o: 'rdp_layout_no'
      v: 'no'

## sesman.ini

- name: xrdp-config - set max connected sessions
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Sessions
    option: MaxSessions
    value: '{{ xrdp_server_max_sessions|int|string }}'
    no_extra_spaces: true
    mode: 0644
  register: xrdp_server_max_sessions_config

- name: xrdp-config - set idle timout
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Sessions
    option: IdleTimeLimit
    value: '{{ xrdp_server_idle_timeout_seconds|int|string }}'
    no_extra_spaces: true
    mode: 0644
  register: xrdp_server_idle_timeout_seconds_config

- name: xrdp-config - set disconnected timout
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Sessions
    option: DisconnectedTimeLimit
    value: '{{ xrdp_server_disconnected_timeout_seconds|int|string }}'
    no_extra_spaces: true
    mode: 0644
  register: xrdp_server_disconnected_timeout_seconds_config

- name: xrdp-config - kill disconnected sessions
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Sessions
    option: KillDisconnected
    value: '{{ "true" if xrdp_server_disconnected_timeout_seconds > 0 else "false" }}'
    no_extra_spaces: true
    mode: 0644

- name: xrdp-config - allow root login
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Security
    option: AllowRootLogin
    value: '{{ xrdp_server_allow_root_login|lower }}'
    no_extra_spaces: true
    mode: 0644
  register: xrdp_server_allow_root_login_config

- name: xrdp-config - restict outbound clipboard
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Security
    option: RestrictOutboundClipboard
    value: '{{ xrdp_server_restrict_outbound_clipboard|lower }}'
    no_extra_spaces: true
    mode: 0644
  register: xrdp_server_restrict_outbound_clipboard_config

- name: xrdp-config - check users against groups
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Security
    option: AlwaysGroupCheck
    value: '{{ xrdp_server_group_check|lower }}'
    no_extra_spaces: true
    mode: 0644
  register: xrdp_server_group_check_config

- name: xrdp-config - set log level
  ini_file:
    path: /etc/xrdp/sesman.ini
    section: Logging
    option: '{{ item }}'
    value: '{{ xrdp_server_loglevel|upper }}'
    no_extra_spaces: true
    mode: 0644
  loop:
    - LogLevel
    - SyslogLevel
  register: xrdp_server_loglevel_config

## xrdp.ini

- name: xrdp-config - remove unused options for xvnc
  ini_file:
    path: /etc/xrdp/xrdp.ini
    section: '{{ item }}'
    state: absent
    mode: 0644
  loop:
    - neutrinordp-any
    - vnc-any
    - xorg
  register: remove_unused
  when: xrdp_server_tigervnc_enable

- name: xrdp-config - remove unused options for xorgxrdp
  ini_file:
    path: /etc/xrdp/xrdp.ini
    section: '{{ item }}'
    state: absent
    mode: 0644
  loop:
    - neutrinordp-any
    - vnc-any
    - Xvnc
  register: remove_unused
  when: not xrdp_server_tigervnc_enable

- name: xrdp-config - set log level
  ini_file:
    path: /etc/xrdp/xrdp.ini
    section: Logging
    option: '{{ item }}'
    value: '{{ xrdp_server_loglevel|upper }}'
    no_extra_spaces: true
    mode: 0644
  loop:
    - LogLevel
    - SyslogLevel

## restart

- name: xrdp-config - restart xrdp services
  systemd:
    name: '{{ item }}'
    state: restarted
  loop:
    - xrdp
    - xrdp-sesman
  when:
    - keyboard_file is changed or
      keyboard_config is changed or
      xrdp_server_max_sessions_config is changed or
      xrdp_server_idle_timeout_seconds_config is changed or
      xrdp_server_disconnected_timeout_seconds_config is changed or
      xrdp_server_allow_root_login_config is changed or
      xrdp_server_restrict_outbound_clipboard_config is changed or
      xrdp_server_group_check_config is changed or
      xrdp_server_loglevel_config is changed or
      remove_unused is changed

