# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  boxes = [
    { :name => "focal", :box => "ubuntu/focal64" },
  ]
  last_octet = 10
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.box = opts[:box]
      config.vm.network "private_network", ip: "10.10.10.#{last_octet}"
      last_octet += 1
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.linked_clone = true
      end
      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible: check",  type: "ansible", run: "always" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "test.yml"
          ansible.limit = "all"
          ansible.raw_arguments = ["--check", "--diff"]
        end
        config.vm.provision "ansible: run", type: "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "test.yml"
          ansible.limit = "all"
        end
      end
    end
  end
end
